name: Daily Scheduled Bump
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
#    - cron: '30 9 * * *'
      #  push:
      #    branches: [ main ]


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: CGA1123/dependabot-lein-runner@main
        with:
          token: ${{ secrets.PATOKEN }}
          repository: ${{ github.GITHUB_TOKEN }}
          registries: https://maven.pkg.github.com/etolbakov/test-pr-repo