name: Daily Scheduled Bump
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
#    - cron: '30 9 * * *'
      #  push:
      #    branches: [ main ]


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: CGA1123/dependabot-lein-runner@main
        env:
          GH_PACKAGES_USR: x-access-token
          GH_PACKAGES_PSW: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}